/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdaptersRouteImport } from './routes/adapters'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as CensoRouteImport } from './routes/censo'
import { Route as CoberturaRouteImport } from './routes/cobertura'
import { Route as FamiliasRouteImport } from './routes/familias'
import { Route as FontesRouteImport } from './routes/fontes'
import { Route as ItensRouteImport } from './routes/itens'
import { Route as MatrizRouteImport } from './routes/matriz'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as OrgaosRouteImport } from './routes/orgaos'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as PrioridadesRouteImport } from './routes/prioridades'
import { Route as ValidacaoRouteImport } from './routes/validacao'
import { Route as FamiliasIndexRouteImport } from './routes/familias/index'
import { Route as FamiliasFamilyRouteImport } from './routes/familias/$family'
import { Route as FontesIndexRouteImport } from './routes/fontes/index'
import { Route as FontesIdRouteImport } from './routes/fontes/$id'
import { Route as ItensIndexRouteImport } from './routes/itens/index'
import { Route as ItensIdRouteImport } from './routes/itens/$id'
import { Route as OportunidadesIndexRouteImport } from './routes/oportunidades/index'
import { Route as OportunidadesIdRouteImport } from './routes/oportunidades/$id'
import { Route as OrgaosIndexRouteImport } from './routes/orgaos/index'
import { Route as OrgaosIdRouteImport } from './routes/orgaos/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptersRoute = AdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const CensoRoute = CensoRouteImport.update({
  id: '/censo',
  path: '/censo',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaRoute = CoberturaRouteImport.update({
  id: '/cobertura',
  path: '/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliasRoute = FamiliasRouteImport.update({
  id: '/familias',
  path: '/familias',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesRoute = FontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const ItensRoute = ItensRouteImport.update({
  id: '/itens',
  path: '/itens',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrizRoute = MatrizRouteImport.update({
  id: '/matriz',
  path: '/matriz',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgaosRoute = OrgaosRouteImport.update({
  id: '/orgaos',
  path: '/orgaos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioridadesRoute = PrioridadesRouteImport.update({
  id: '/prioridades',
  path: '/prioridades',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidacaoRoute = ValidacaoRouteImport.update({
  id: '/validacao',
  path: '/validacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliasIndexRoute = FamiliasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FamiliasRoute,
} as any)
const FamiliasFamilyRoute = FamiliasFamilyRouteImport.update({
  id: '/$family',
  path: '/$family',
  getParentRoute: () => FamiliasRoute,
} as any)
const FontesIndexRoute = FontesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FontesRoute,
} as any)
const FontesIdRoute = FontesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FontesRoute,
} as any)
const ItensIndexRoute = ItensIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItensRoute,
} as any)
const ItensIdRoute = ItensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ItensRoute,
} as any)
const OportunidadesIndexRoute = OportunidadesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OportunidadesRoute,
} as any)
const OportunidadesIdRoute = OportunidadesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OportunidadesRoute,
} as any)
const OrgaosIndexRoute = OrgaosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgaosRoute,
} as any)
const OrgaosIdRoute = OrgaosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrgaosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/alertas': typeof AlertasRoute
  '/busca': typeof BuscaRoute
  '/censo': typeof CensoRoute
  '/cobertura': typeof CoberturaRoute
  '/familias': typeof FamiliasRouteWithChildren
  '/fontes': typeof FontesRouteWithChildren
  '/itens': typeof ItensRouteWithChildren
  '/matriz': typeof MatrizRoute
  '/oportunidades': typeof OportunidadesRouteWithChildren
  '/orgaos': typeof OrgaosRouteWithChildren
  '/planejamento': typeof PlanejamentoRoute
  '/prioridades': typeof PrioridadesRoute
  '/validacao': typeof ValidacaoRoute
  '/familias/$family': typeof FamiliasFamilyRoute
  '/fontes/$id': typeof FontesIdRoute
  '/itens/$id': typeof ItensIdRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
  '/orgaos/$id': typeof OrgaosIdRoute
  '/familias/': typeof FamiliasIndexRoute
  '/fontes/': typeof FontesIndexRoute
  '/itens/': typeof ItensIndexRoute
  '/oportunidades/': typeof OportunidadesIndexRoute
  '/orgaos/': typeof OrgaosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/alertas': typeof AlertasRoute
  '/busca': typeof BuscaRoute
  '/censo': typeof CensoRoute
  '/cobertura': typeof CoberturaRoute
  '/matriz': typeof MatrizRoute
  '/planejamento': typeof PlanejamentoRoute
  '/prioridades': typeof PrioridadesRoute
  '/validacao': typeof ValidacaoRoute
  '/familias/$family': typeof FamiliasFamilyRoute
  '/fontes/$id': typeof FontesIdRoute
  '/itens/$id': typeof ItensIdRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
  '/orgaos/$id': typeof OrgaosIdRoute
  '/familias': typeof FamiliasIndexRoute
  '/fontes': typeof FontesIndexRoute
  '/itens': typeof ItensIndexRoute
  '/oportunidades': typeof OportunidadesIndexRoute
  '/orgaos': typeof OrgaosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/alertas': typeof AlertasRoute
  '/busca': typeof BuscaRoute
  '/censo': typeof CensoRoute
  '/cobertura': typeof CoberturaRoute
  '/familias': typeof FamiliasRouteWithChildren
  '/fontes': typeof FontesRouteWithChildren
  '/itens': typeof ItensRouteWithChildren
  '/matriz': typeof MatrizRoute
  '/oportunidades': typeof OportunidadesRouteWithChildren
  '/orgaos': typeof OrgaosRouteWithChildren
  '/planejamento': typeof PlanejamentoRoute
  '/prioridades': typeof PrioridadesRoute
  '/validacao': typeof ValidacaoRoute
  '/familias/$family': typeof FamiliasFamilyRoute
  '/fontes/$id': typeof FontesIdRoute
  '/itens/$id': typeof ItensIdRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
  '/orgaos/$id': typeof OrgaosIdRoute
  '/familias/': typeof FamiliasIndexRoute
  '/fontes/': typeof FontesIndexRoute
  '/itens/': typeof ItensIndexRoute
  '/oportunidades/': typeof OportunidadesIndexRoute
  '/orgaos/': typeof OrgaosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adapters'
    | '/alertas'
    | '/busca'
    | '/censo'
    | '/cobertura'
    | '/familias'
    | '/fontes'
    | '/itens'
    | '/matriz'
    | '/oportunidades'
    | '/orgaos'
    | '/planejamento'
    | '/prioridades'
    | '/validacao'
    | '/familias/$family'
    | '/fontes/$id'
    | '/itens/$id'
    | '/oportunidades/$id'
    | '/orgaos/$id'
    | '/familias/'
    | '/fontes/'
    | '/itens/'
    | '/oportunidades/'
    | '/orgaos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adapters'
    | '/alertas'
    | '/busca'
    | '/censo'
    | '/cobertura'
    | '/matriz'
    | '/planejamento'
    | '/prioridades'
    | '/validacao'
    | '/familias/$family'
    | '/fontes/$id'
    | '/itens/$id'
    | '/oportunidades/$id'
    | '/orgaos/$id'
    | '/familias'
    | '/fontes'
    | '/itens'
    | '/oportunidades'
    | '/orgaos'
  id:
    | '__root__'
    | '/'
    | '/adapters'
    | '/alertas'
    | '/busca'
    | '/censo'
    | '/cobertura'
    | '/familias'
    | '/fontes'
    | '/itens'
    | '/matriz'
    | '/oportunidades'
    | '/orgaos'
    | '/planejamento'
    | '/prioridades'
    | '/validacao'
    | '/familias/$family'
    | '/fontes/$id'
    | '/itens/$id'
    | '/oportunidades/$id'
    | '/orgaos/$id'
    | '/familias/'
    | '/fontes/'
    | '/itens/'
    | '/oportunidades/'
    | '/orgaos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptersRoute: typeof AdaptersRoute
  AlertasRoute: typeof AlertasRoute
  BuscaRoute: typeof BuscaRoute
  CensoRoute: typeof CensoRoute
  CoberturaRoute: typeof CoberturaRoute
  FamiliasRoute: typeof FamiliasRouteWithChildren
  FontesRoute: typeof FontesRouteWithChildren
  ItensRoute: typeof ItensRouteWithChildren
  MatrizRoute: typeof MatrizRoute
  OportunidadesRoute: typeof OportunidadesRouteWithChildren
  OrgaosRoute: typeof OrgaosRouteWithChildren
  PlanejamentoRoute: typeof PlanejamentoRoute
  PrioridadesRoute: typeof PrioridadesRoute
  ValidacaoRoute: typeof ValidacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapters': {
      id: '/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof AdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/censo': {
      id: '/censo'
      path: '/censo'
      fullPath: '/censo'
      preLoaderRoute: typeof CensoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura': {
      id: '/cobertura'
      path: '/cobertura'
      fullPath: '/cobertura'
      preLoaderRoute: typeof CoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familias': {
      id: '/familias'
      path: '/familias'
      fullPath: '/familias'
      preLoaderRoute: typeof FamiliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes': {
      id: '/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itens': {
      id: '/itens'
      path: '/itens'
      fullPath: '/itens'
      preLoaderRoute: typeof ItensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matriz': {
      id: '/matriz'
      path: '/matriz'
      fullPath: '/matriz'
      preLoaderRoute: typeof MatrizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgaos': {
      id: '/orgaos'
      path: '/orgaos'
      fullPath: '/orgaos'
      preLoaderRoute: typeof OrgaosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prioridades': {
      id: '/prioridades'
      path: '/prioridades'
      fullPath: '/prioridades'
      preLoaderRoute: typeof PrioridadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validacao': {
      id: '/validacao'
      path: '/validacao'
      fullPath: '/validacao'
      preLoaderRoute: typeof ValidacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familias/': {
      id: '/familias/'
      path: '/'
      fullPath: '/familias/'
      preLoaderRoute: typeof FamiliasIndexRouteImport
      parentRoute: typeof FamiliasRoute
    }
    '/familias/$family': {
      id: '/familias/$family'
      path: '/$family'
      fullPath: '/familias/$family'
      preLoaderRoute: typeof FamiliasFamilyRouteImport
      parentRoute: typeof FamiliasRoute
    }
    '/fontes/': {
      id: '/fontes/'
      path: '/'
      fullPath: '/fontes/'
      preLoaderRoute: typeof FontesIndexRouteImport
      parentRoute: typeof FontesRoute
    }
    '/fontes/$id': {
      id: '/fontes/$id'
      path: '/$id'
      fullPath: '/fontes/$id'
      preLoaderRoute: typeof FontesIdRouteImport
      parentRoute: typeof FontesRoute
    }
    '/itens/': {
      id: '/itens/'
      path: '/'
      fullPath: '/itens/'
      preLoaderRoute: typeof ItensIndexRouteImport
      parentRoute: typeof ItensRoute
    }
    '/itens/$id': {
      id: '/itens/$id'
      path: '/$id'
      fullPath: '/itens/$id'
      preLoaderRoute: typeof ItensIdRouteImport
      parentRoute: typeof ItensRoute
    }
    '/oportunidades/': {
      id: '/oportunidades/'
      path: '/'
      fullPath: '/oportunidades/'
      preLoaderRoute: typeof OportunidadesIndexRouteImport
      parentRoute: typeof OportunidadesRoute
    }
    '/oportunidades/$id': {
      id: '/oportunidades/$id'
      path: '/$id'
      fullPath: '/oportunidades/$id'
      preLoaderRoute: typeof OportunidadesIdRouteImport
      parentRoute: typeof OportunidadesRoute
    }
    '/orgaos/': {
      id: '/orgaos/'
      path: '/'
      fullPath: '/orgaos/'
      preLoaderRoute: typeof OrgaosIndexRouteImport
      parentRoute: typeof OrgaosRoute
    }
    '/orgaos/$id': {
      id: '/orgaos/$id'
      path: '/$id'
      fullPath: '/orgaos/$id'
      preLoaderRoute: typeof OrgaosIdRouteImport
      parentRoute: typeof OrgaosRoute
    }
  }
}

interface FamiliasRouteChildren {
  FamiliasFamilyRoute: typeof FamiliasFamilyRoute
  FamiliasIndexRoute: typeof FamiliasIndexRoute
}

const FamiliasRouteChildren: FamiliasRouteChildren = {
  FamiliasFamilyRoute: FamiliasFamilyRoute,
  FamiliasIndexRoute: FamiliasIndexRoute,
}

const FamiliasRouteWithChildren = FamiliasRoute._addFileChildren(
  FamiliasRouteChildren,
)

interface FontesRouteChildren {
  FontesIdRoute: typeof FontesIdRoute
  FontesIndexRoute: typeof FontesIndexRoute
}

const FontesRouteChildren: FontesRouteChildren = {
  FontesIdRoute: FontesIdRoute,
  FontesIndexRoute: FontesIndexRoute,
}

const FontesRouteWithChildren =
  FontesRoute._addFileChildren(FontesRouteChildren)

interface ItensRouteChildren {
  ItensIdRoute: typeof ItensIdRoute
  ItensIndexRoute: typeof ItensIndexRoute
}

const ItensRouteChildren: ItensRouteChildren = {
  ItensIdRoute: ItensIdRoute,
  ItensIndexRoute: ItensIndexRoute,
}

const ItensRouteWithChildren = ItensRoute._addFileChildren(ItensRouteChildren)

interface OportunidadesRouteChildren {
  OportunidadesIdRoute: typeof OportunidadesIdRoute
  OportunidadesIndexRoute: typeof OportunidadesIndexRoute
}

const OportunidadesRouteChildren: OportunidadesRouteChildren = {
  OportunidadesIdRoute: OportunidadesIdRoute,
  OportunidadesIndexRoute: OportunidadesIndexRoute,
}

const OportunidadesRouteWithChildren = OportunidadesRoute._addFileChildren(
  OportunidadesRouteChildren,
)

interface OrgaosRouteChildren {
  OrgaosIdRoute: typeof OrgaosIdRoute
  OrgaosIndexRoute: typeof OrgaosIndexRoute
}

const OrgaosRouteChildren: OrgaosRouteChildren = {
  OrgaosIdRoute: OrgaosIdRoute,
  OrgaosIndexRoute: OrgaosIndexRoute,
}

const OrgaosRouteWithChildren =
  OrgaosRoute._addFileChildren(OrgaosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptersRoute: AdaptersRoute,
  AlertasRoute: AlertasRoute,
  BuscaRoute: BuscaRoute,
  CensoRoute: CensoRoute,
  CoberturaRoute: CoberturaRoute,
  FamiliasRoute: FamiliasRouteWithChildren,
  FontesRoute: FontesRouteWithChildren,
  ItensRoute: ItensRouteWithChildren,
  MatrizRoute: MatrizRoute,
  OportunidadesRoute: OportunidadesRouteWithChildren,
  OrgaosRoute: OrgaosRouteWithChildren,
  PlanejamentoRoute: PlanejamentoRoute,
  PrioridadesRoute: PrioridadesRoute,
  ValidacaoRoute: ValidacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
